### PR TITLE
Minor UI enhancements

### PR DESCRIPTION
**Pull request by Fatmali**

### CODE REVIEW

**Comment by Naveed1842** [comment]
Fatime why project is not running.Can you share with me the node version and npm version of your laptop?

**Comment by enyachoke** [comment]
@Naveed1842  this project is just an editor really the best place your want to look for a way to handle forms in your project is https://github.com/AMPATH/ng2-amrs/blob/master/src/app/patient-dashboard/common/formentry/formentry.component.ts. By the way have you tried to build https://github.com/AMPATH/ng2-amrs

**Comment by Fatmali** [comment]
@Naveed1842 node version 6.11.1 and npm 3.10.10. What is the error message you are getting? Below are the steps to have it running in your computer.

**1. git clone https://github.com/AMPATH/ng2-openmrs-formbuilder.git
2. npm install
3. ng serve**

**Comment by Naveed1842** [comment]
I run form-builder successfully.Do you have any documentation for this
project upon reading that I understand your code.What is the purpose of
reference form in form builder application.?

**Comment by Naveed1842** [comment]
Hi enyachoke.I am trying to build ng2-amrs but I am getting error.I want to ask what is the purpose of reference form in form builder.?

**Comment by Naveed1842** [comment]
When I try to build ng2-amrs I am getting this error.

> ERROR

 in Error encountered resolving symbol values statically. Calling function 'ChartModule', function calls ar
e not supported. Consider replacing the function or lambda with a reference to an exported function, resolving s
ymbol ReportingUtilitiesModule in D:/ORIC2017/25MondayNg2/ng2-amrs/src/app/reporting-utilities/reporting-utiliti
es.module.ts, resolving symbol ReportingUtilitiesModule in D:/ORIC2017/25MondayNg2/ng2-amrs/src/app/reporting-ut
ilities/reporting-utilities.module.ts

ERROR in multi ./src/styles.css
Module not found: Error: Can't resolve 'D:\ORIC2017\25MondayNg2\ng2-amrs\src\styles.css' in 'D:\ORIC2017\25Monda
yNg2\ng2-amrs\node_modules\@angular\cli\models\webpack-configs'
 @ multi ./src/styles.css

ERROR in ./src/polyfills.ts
Module not found: Error: Can't resolve 'zonejs' in 'D:\ORIC2017\25MondayNg2\ng2-amrs\src'
 @ ./src/polyfills.ts 37:0-16
 @ multi ./src/polyfills.ts

ERROR in ./src/styles/styles.scss
Module build failed: Error: ENOENT: no such file or directory, scandir 'D:\ORIC2017\25MondayNg2\ng2-amrs\node_mo
dules\node-sass\vendor'
    at Error (native)
    at Object.fs.readdirSync (fs.js:952:18)
    at Object.getInstalledBinaries (D:\ORIC2017\25MondayNg2\ng2-amrs\node_modules\node-sass\lib\extensions.js:12
4:13)
    at foundBinariesList (D:\ORIC2017\25MondayNg2\ng2-amrs\node_modules\node-sass\lib\errors.js:20:15)
    at foundBinaries (D:\ORIC2017\25MondayNg2\ng2-amrs\node_modules\node-sass\lib\errors.js:15:5)
    at Object.module.exports.missingBinary (D:\ORIC2017\25MondayNg2\ng2-amrs\node_modules\node-sass\lib\errors.j
s:45:5)
    at module.exports (D:\ORIC2017\25MondayNg2\ng2-amrs\node_modules\node-sass\lib\binding.js:15:30)
    at Object.<anonymous> (D:\ORIC2017\25MondayNg2\ng2-amrs\node_modules\node-sass\lib\index.js:14:35)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (D:\ORIC2017\25MondayNg2\ng2-amrs\node_modules\sass-loader\lib\loader.js:3:14)
 @ ./src/app/app.module.ts 2:0-31
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://localhost:4200 ./src/main.ts
webpack: Failed to compile.

>

**Comment by enyachoke** [comment]
@Naveed1842 What about if your run npm start. Components enable reusability but you should ignore them for now.

**Comment by Naveed1842** [comment]
Running npm run.I got these errors.
ERROR in ./~/css-loader!./~/sass-loader/lib/loader.js!./src/styles/styles.scss
Module build failed: Error: Cannot find module 'node-sass'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (D:\ORIC2017\ng2-amrs-master\ng2-amrs\node_modules\sass-loader\lib\loader.js:3:14)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at loadLoader (D:\ORIC2017\ng2-amrs-master\ng2-amrs\node_modules\loader-runner\lib\loadLoader.js:13:17)
    at iteratePitchingLoaders (D:\ORIC2017\ng2-amrs-master\ng2-amrs\node_modules\loader-runner\lib\LoaderRunner.js:169:2)
    at iteratePitchingLoaders (D:\ORIC2017\ng2-amrs-master\ng2-amrs\node_modules\loader-runner\lib\LoaderRunner.js:165:10)
    at D:\ORIC2017\ng2-amrs-master\ng2-amrs\node_modules\loader-runner\lib\LoaderRunner.js:173:18
    at loadLoader (D:\ORIC2017\ng2-amrs-master\ng2-amrs\node_modules\loader-runner\lib\loadLoader.js:36:3)
    at iteratePitchingLoaders (D:\ORIC2017\ng2-amrs-master\ng2-amrs\node_modules\loader-runner\lib\LoaderRunner.js:169:2)
    at runLoaders (D:\ORIC2017\ng2-amrs-master\ng2-amrs\node_modules\loader-runner\lib\LoaderRunner.js:362:2)
    at NormalModule.doBuild (D:\ORIC2017\ng2-amrs-master\ng2-amrs\node_modules\webpack\lib\NormalModule.js:179:3)
    at NormalModule.build (D:\ORIC2017\ng2-amrs-master\ng2-amrs\node_modules\webpack\lib\NormalModule.js:268:15)
    at Compilation.buildModule (D:\ORIC2017\ng2-amrs-master\ng2-amrs\node_modules\webpack\lib\Compilation.js:142:10)
 @ ./src/styles/styles.scss 4:14-124
 @ ./src/app/app.module.ts
 @ ./src/app/index.ts
 @ ./src/main.browser.ts
 @ multi (webpack)-dev-server/client?http://localhost:3000 ./src/main.browser.ts
Child html-webpack-plugin for "index.html":
    chunk    {0} index.html 546 kB [entry] [rendered]
        [0] ./~/lodash/lodash.js 540 kB {0} [built]
            [] -> factory:16ms building:328ms = 344ms
        [1] ./~/html-webpack-plugin/lib/loader.js!./src/index.html 5.63 kB {0} [built]
             factory:172ms building:172ms = 344ms
        [2] (webpack)/buildin/global.js 509 bytes {0} [built]
            [] -> factory:125ms building:3750ms = 3875ms
        [3] (webpack)/buildin/module.js 517 bytes {0} [built]
            [] -> factory:125ms building:3750ms = 3875ms
webpack: Failed to compile.

**Comment by Naveed1842** [comment]
npm start 
I just get this latest runing npm start

> Ampath_Point_of_Care@2.6.0-SNAPSHOT start D:\ORIC2017\ng2-amrs-master\ng2-amrs
> npm run server:dev

npm WARN invalid config loglevel="notice"

> Ampath_Point_of_Care@2.6.0-SNAPSHOT server:dev D:\ORIC2017\ng2-amrs-master\ng2-amrs
> npm run webpack-dev-server -- --config config/webpack.dev.js --open --progress --profile --watch --content-base src/

npm WARN invalid config loglevel="notice"

> Ampath_Point_of_Care@2.6.0-SNAPSHOT webpack-dev-server D:\ORIC2017\ng2-amrs-master\ng2-amrs
> node --max_old_space_size=4096 node_modules/webpack-dev-server/bin/webpack-dev-server.js "--config" "config/webpack.dev.js" "--open" "--progress" "--profile" "--watch" "--content-base" "src/"

module.js:471
    throw err;
    ^

Error: Cannot find module 'D:\ORIC2017\ng2-amrs-master\ng2-amrs\node_modules\webpack-dev-server\bin\webpack-dev-server.js'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:504:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! Ampath_Point_of_Care@2.6.0-SNAPSHOT webpack-dev-server: `node --max_old_space_size=4096 node_modules/webpack-dev-server/bin/webpack-dev-server.js "--config" "config/webpack.dev.js" "--open" "--progress" "--profile" "--watch" "--content-base" "src/"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the Ampath_Point_of_Care@2.6.0-SNAPSHOT webpack-dev-server script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Naveed\AppData\Roaming\npm-cache\_logs\2017-09-25T12_07_08_600Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! Ampath_Point_of_Care@2.6.0-SNAPSHOT server:dev: `npm run webpack-dev-server -- --config config/webpack.dev.js --open --progress --profile --watch --content-base src/`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the Ampath_Point_of_Care@2.6.0-SNAPSHOT server:dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Naveed\AppData\Roaming\npm-cache\_logs\2017-09-25T12_07_08_632Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! Ampath_Point_of_Care@2.6.0-SNAPSHOT start: `npm run server:dev`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the Ampath_Point_of_Care@2.6.0-SNAPSHOT start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Naveed\AppData\Roaming\npm-cache\_logs\2017-09-25T12_07_08_663Z-debug.log

**Comment by enyachoke** [comment]
npm install webpack-dev-server

**Comment by Fatmali** [comment]
@Naveed1842 I will write a documentation soon. The reference forms is a feature to allow importing form elements from existing forms in order to avoid repetition.

**Comment by Naveed1842** [comment]
Thanks for the reply.One thing how payload is generated through ng2-openmrs form entry demo.What is the storage procedure to save that payload in openmrs.We are trying to use form-builder with openmrs to deal with openmrs forms.Please explain it in your free time.
Thanks.

**Comment by Naveed1842** [comment]
@enyachoke  after running that command got this error.$ npm start

> Ampath_Point_of_Care@2.6.0-SNAPSHOT start D:\ORIC2017\ng2-amrs-master\ng2-amrs
> npm run server:dev

npm WARN invalid config loglevel="notice"

> Ampath_Point_of_Care@2.6.0-SNAPSHOT server:dev D:\ORIC2017\ng2-amrs-master\ng2-amrs
> npm run webpack-dev-server -- --config config/webpack.dev.js --open --progress --profile --watch --content-base src/

npm WARN invalid config loglevel="notice"

> Ampath_Point_of_Care@2.6.0-SNAPSHOT webpack-dev-server D:\ORIC2017\ng2-amrs-master\ng2-amrs
> node --max_old_space_size=4096 node_modules/webpack-dev-server/bin/webpack-dev-server.js "--config" "config/webpack.dev.js" "--open" "--progress" "--profile" "--watch" "--content-base" "src/"

module.js:471
    throw err;
    ^

Error: Cannot find module 'webpack'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (D:\ORIC2017\ng2-amrs-master\ng2-amrs\node_modules\webpack-dev-server\lib\Server.js:15:17)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! Ampath_Point_of_Care@2.6.0-SNAPSHOT webpack-dev-server: `node --max_old_space_size=4096 node_modules/webpack-dev-server/bin/webpack-dev-server.js "--config" "config/webpack.dev.js" "--open" "--progress" "--profile" "--watch" "--content-base" "src/"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the Ampath_Point_of_Care@2.6.0-SNAPSHOT webpack-dev-server script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Naveed\AppData\Roaming\npm-cache\_logs\2017-09-26T05_00_11_356Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! Ampath_Point_of_Care@2.6.0-SNAPSHOT server:dev: `npm run webpack-dev-server -- --config config/webpack.dev.js --open --progress --profile --watch --content-base src/`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the Ampath_Point_of_Care@2.6.0-SNAPSHOT server:dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Naveed\AppData\Roaming\npm-cache\_logs\2017-09-26T05_00_11_544Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! Ampath_Point_of_Care@2.6.0-SNAPSHOT start: `npm run server:dev`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the Ampath_Point_of_Care@2.6.0-SNAPSHOT start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:

**Comment by enyachoke** [comment]
Hi @Naveed1842 unless you are new to node this should be relatively easy things to sort the message is very clear it can't find the webpack module so just install that.
npm install webpack
also install webpack cli

npm install webpack-cli -g

**Comment by enyachoke** [comment]
@Naveed1842  about how you save the payload from formentry that is is something your should be able to send to openmrs its is basically an encounter payload.

**Comment by Naveed1842** [comment]
@enyachoke 
got these error after several installation.I am pretty new to node you are right.
WARNING in ./src/app/version.json
Module build failed: SyntaxError: Unexpected end of JSON input
    at Object.parse (native)
    at Object.module.exports (D:\ORIC2017\ng2-amrs-master\ng2-amrs\node_modules\json-loader\index.js:4:49)
 @ ./src/app/build-version/build-version.component.ts 11:23-49
 @ ./src/app/build-version/index.ts
 @ ./src/app/shared/ngamrs-shared.module.ts
 @ ./src/app/app.module.ts
 @ ./src/app/index.ts
 @ ./src/main.browser.ts
 @ multi (webpack)-dev-server/client?http://localhost:3000 ./src/main.browser.ts

ERROR in ./src/app/app.module.ts
Module not found: Error: Can't resolve 'ngx-bootstrap/modal' in 'D:\ORIC2017\ng2-amrs-master\ng2-amrs\src\app'
 @ ./src/app/app.module.ts 34:0-50
 @ ./src/app/index.ts
 @ ./src/main.browser.ts
 @ multi (webpack)-dev-server/client?http://localhost:3000 ./src/main.browser.ts

ERROR in ./src/app/shared/ngamrs-shared.module.ts
Module not found: Error: Can't resolve 'ngx-bootstrap/modal' in 'D:\ORIC2017\ng2-amrs-master\ng2-amrs\src\app\shared'
 @ ./src/app/shared/ngamrs-shared.module.ts 9:0-50
 @ ./src/app/app.module.ts
 @ ./src/app/index.ts
 @ ./src/main.browser.ts
 @ multi (webpack)-dev-server/client?http://localhost:3000 ./src/main.browser.ts

ERROR in ./src/app/app-settings/app-settings.module.ts
Module not found: Error: Can't resolve 'ngx-bootstrap/modal' in 'D:\ORIC2017\ng2-amrs-master\ng2-amrs\src\app\app-settings'
 @ ./src/app/app-settings/app-settings.module.ts 9:0-50
 @ ./src/app/openmrs-api/openmrs-api.module.ts
 @ ./src/app/shared/ngamrs-shared.module.ts
 @ ./src/app/app.module.ts
 @ ./src/app/index.ts
 @ ./src/main.browser.ts
 @ multi (webpack)-dev-server/client?http://localhost:3000 ./src/main.browser.ts

ERROR in ./src/app/app-settings/app-settings.component.ts
Module not found: Error: Can't resolve 'ngx-bootstrap/modal' in 'D:\ORIC2017\ng2-amrs-master\ng2-amrs\src\app\app-settings'
 @ ./src/app/app-settings/app-settings.component.ts 7:0-53
 @ ./src/app/app-settings/index.ts
 @ ./src/app/openmrs-api/user.service.ts
 @ ./src/app/shared/app-analytics/app-feature-analytics.service.ts
 @ ./src/app/app.module.ts
 @ ./src/app/index.ts
 @ ./src/main.browser.ts
 @ multi (webpack)-dev-server/client?http://localhost:3000 ./src/main.browser.ts

ERROR in ./src/app/patient-dashboard/common/patient-encounters/patient-encounter-observations.component.ts
Module not found: Error: Can't resolve 'ngx-bootstrap/modal' in 'D:\ORIC2017\ng2-amrs-master\ng2-amrs\src\app\patient-dashboard\common\patient-encounters'
 @ ./src/app/patient-dashboard/common/patient-encounters/patient-encounter-observations.component.ts 7:0-53
 @ ./src/app/patient-dashboard/common/patient-dashboard.common.module.ts
 @ ./src/app/patient-dashboard/patient-dashboard.module.ts
 @ ./src/app/main-dashboard/main-dashboard-routing.ts
 @ ./src/app/main-dashboard/main-dashboard.module.ts
 @ ./src/app/app-routing.module.ts
 @ ./src/app/app.module.ts
 @ ./src/app/index.ts
 @ ./src/main.browser.ts
 @ multi (webpack)-dev-server/client?http://localhost:3000 ./src/main.browser.ts

ERROR in ./~/angular-calendar/dist/esm/src/calendar.module.js
Module not found: Error: Can't resolve 'angular-resizable-element' in 'D:\ORIC2017\ng2-amrs-master\ng2-amrs\node_modules\angular-calendar\dist\esm\src'
 @ ./~/angular-calendar/dist/esm/src/calendar.module.js 3:0-60
 @ ./~/angular-calendar/dist/esm/src/index.js
 @ ./src/app/data-analytics-dashboard/data-analytics.module.ts
 @ ./src/app/main-dashboard/main-dashboard-routing.ts
 @ ./src/app/main-dashboard/main-dashboard.module.ts
 @ ./src/app/app-routing.module.ts
 @ ./src/app/app.module.ts
 @ ./src/app/index.ts
 @ ./src/main.browser.ts
 @ multi (webpack)-dev-server/client?http://localhost:3000 ./src/main.browser.ts

ERROR in ./~/angular-calendar/dist/esm/src/calendar.module.js
Module not found: Error: Can't resolve 'angular-draggable-droppable' in 'D:\ORIC2017\ng2-amrs-master\ng2-amrs\node_modules\angular-calendar\dist\esm\src'
 @ ./~/angular-calendar/dist/esm/src/calendar.module.js 4:0-81
 @ ./~/angular-calendar/dist/esm/src/index.js
 @ ./src/app/data-analytics-dashboard/data-analytics.module.ts
 @ ./src/app/main-dashboard/main-dashboard-routing.ts
 @ ./src/app/main-dashboard/main-dashboard.module.ts
 @ ./src/app/app-routing.module.ts
 @ ./src/app/app.module.ts
 @ ./src/app/index.ts
 @ ./src/main.browser.ts
 @ multi (webpack)-dev-server/client?http://localhost:3000 ./src/main.browser.ts

ERROR in ./~/angular-calendar/dist/esm/src/components/month/calendarMonthView.component.js
Module not found: Error: Can't resolve 'calendar-utils' in 'D:\ORIC2017\ng2-amrs-master\ng2-amrs\node_modules\angular-calendar\dist\esm\src\components\month'
 @ ./~/angular-calendar/dist/esm/src/components/month/calendarMonthView.component.js 2:0-65
 @ ./~/angular-calendar/dist/esm/src/index.js
 @ ./src/app/data-analytics-dashboard/data-analytics.module.ts
 @ ./src/app/main-dashboard/main-dashboard-routing.ts
 @ ./src/app/main-dashboard/main-dashboard.module.ts
 @ ./src/app/app-routing.module.ts
 @ ./src/app/app.module.ts
 @ ./src/app/index.ts
 @ ./src/main.browser.ts
 @ multi (webpack)-dev-server/client?http://localhost:3000 ./src/main.browser.ts

ERROR in ./~/angular-calendar/dist/esm/src/components/day/calendarDayView.component.js
Module not found: Error: Can't resolve 'calendar-utils' in 'D:\ORIC2017\ng2-amrs-master\ng2-amrs\node_modules\angular-calendar\dist\esm\src\components\day'
 @ ./~/angular-calendar/dist/esm/src/components/day/calendarDayView.component.js 2:0-64
 @ ./~/angular-calendar/dist/esm/src/index.js
 @ ./src/app/data-analytics-dashboard/data-analytics.module.ts
 @ ./src/app/main-dashboard/main-dashboard-routing.ts
 @ ./src/app/main-dashboard/main-dashboard.module.ts
 @ ./src/app/app-routing.module.ts
 @ ./src/app/app.module.ts
 @ ./src/app/index.ts
 @ ./src/main.browser.ts
 @ multi (webpack)-dev-server/client?http://localhost:3000 ./src/main.browser.ts

ERROR in ./~/angular-calendar/dist/esm/src/components/week/calendarWeekView.component.js
Module not found: Error: Can't resolve 'calendar-utils' in 'D:\ORIC2017\ng2-amrs-master\ng2-amrs\node_modules\angular-calendar\dist\esm\src\components\week'
 @ ./~/angular-calendar/dist/esm/src/components/week/calendarWeekView.component.js 2:0-64
 @ ./~/angular-calendar/dist/esm/src/index.js
 @ ./src/app/data-analytics-dashboard/data-analytics.module.ts
 @ ./src/app/main-dashboard/main-dashboard-routing.ts
 @ ./src/app/main-dashboard/main-dashboard.module.ts
 @ ./src/app/app-routing.module.ts
 @ ./src/app/app.module.ts
 @ ./src/app/index.ts
 @ ./src/main.browser.ts
 @ multi (webpack)-dev-server/client?http://localhost:3000 ./src/main.browser.ts

ERROR in ./~/ng2-openmrs-formentry/dist/form-entry/form-entry.module.js
Module not found: Error: Can't resolve 'ngx-bootstrap/collapse' in 'D:\ORIC2017\ng2-amrs-master\ng2-amrs\node_modules\ng2-openmrs-formentry\dist\form-entry'
 @ ./~/ng2-openmrs-formentry/dist/form-entry/form-entry.module.js 8:0-56
 @ ./~/ng2-openmrs-formentry/dist/form-entry/index.js
 @ ./~/ng2-openmrs-formentry/dist/index.js
 @ ./src/app/patient-dashboard/common/patient-dashboard.common.module.ts
 @ ./src/app/patient-dashboard/patient-dashboard.module.ts
 @ ./src/app/main-dashboard/main-dashboard-routing.ts
 @ ./src/app/main-dashboard/main-dashboard.module.ts
 @ ./src/app/app-routing.module.ts
 @ ./src/app/app.module.ts
 @ ./src/app/index.ts
 @ ./src/main.browser.ts
 @ multi (webpack)-dev-server/client?http://localhost:3000 ./src/main.browser.ts
Child html-webpack-plugin for "index.html":
    chunk    {0} index.html 546 kB [entry]
         + 4 hidden modules
webpack: Failed to compile.

**Pull request merged**
