### PR TITLE
FOR-9:added select all and select none options for answers

### PR DESCRIPTION
**Pull request by Fatmali**

### CODE REVIEW

**Comment by Naveed1842** [comment]
Hello Fatma what are the credentials for ng2-openmrs-formbuilder.I clone install and compile it but it asking for credentials.I try test and test but it does not work. 

    On Wednesday, September 20, 2017 4:29 PM, Fatma Ali <notifications@github.com> wrote:
 

 Merged #3.—

**Comment by Naveed1842** [comment]
What are credentials for ng2-openmrs-formbuilder

**Comment by Fatmali** [comment]
Hi @Naveed1842 , thanks for showing interest in this project. ng2-openmrs-formbuilder is a tool used to create and edit OpenMRS forms interactively. Could you kindly explain what you are trying to achieve by using this application?

**Comment by Naveed1842** [comment]
we are trying to build front-end for openmrs.We need Form to handle visits and encounter.Can you help me out how can we used your form builder and form entry module in our project?

**Pull request merged**
